apiVersion: v1
kind: Service
metadata:
  name: quotes-service
  labels:
    app: quotes
spec:
  selector:
    app: quotes
  ports:
    - protocol: TCP
      port: 8080       
      targetPort: 80   
  type: LoadBalancer   
