apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
  labels:
    app: quotes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
      - name: quotes
        image: jayasurya5454/quotes:latest
        ports:
        - containerPort: 80  # Nginx listens on port 80 by default
